### ISSUE TITLE
User should see original fields when editing posts

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#469] opened 2023-11-15 00:57 UTC
# Problem
Currently, when a user edits a previously submitted solution post, some of the fields that they entered are combined into the description field. This means that they cannot see or edit the original values that they entered. It also makes it impossible for us to sort posts by certain values, since those fields disappear.

![Screenshot 2023-11-15 at 4 53 35 PM](https://github.com/near/neardevhub-widgets/assets/110252255/5613090b-42f9-4a2d-b068-6190c7904b1c)

# User Story
As a user, I want to see the original values I entered for each input field when I edit the post. If I selected "Yes" to "Are you seeking funding for your solution?" – that value should still hold when I click edit, along with the other fields (e.g. currency, requested amount, requested sponsor).

# Considerations
See more details in https://github.com/near/neardevhub-widgets/issues/285

**Comment by ori-near** [comment] 2023-11-16 00:56
Hi @elliotBraem – I saw that you closed this ticket ... but I still see the same behavior. I'm reopening ticket.

**Comment by elliotBraem** [comment] 2023-12-01 22:28
Because of the high gas due to NEAT transcriptions, these changes failed to deploy after merge.

Waiting until gas goes down. Marking this "in review"

**Comment by elliotBraem** [comment] 2023-12-06 18:34
I can confirm merged. Marking done.

![Screenshot 2023-12-06 at 1 33 48 PM](https://github.com/near/neardevhub-widgets/assets/16282460/b3722884-a62b-4bea-b027-b7e0a1ead553)

**Closed** 2023-12-06 18:34 UTC
