### ISSUE TITLE
User can submit solution when using near.social but not when using near.org

### ISSUE THREAD

**Issue by elliotBraem** [near/neardevhub-widgets#116] opened 2023-04-28 19:23 UTC
**Describe the bug**

I am unable to submit a devgovgig and am getting an error in console: "Error: Class p is missing schema".

**To Reproduce**
1. Go to DevHub
2. Create an Idea or Solution 
3. Fill in the title and description in the Notion doc [here](https://ambitious-spike-28a.notion.site/Idea-No-Code-Widget-Generation-with-Teleport-HQ-b1e690f6099f4107ae5b6ebfebb52ad5)
4. Set labels "near-social", "project", "sprint", "no-code"
5. Click Submit and then confirm once the dialogue comes up.

**Expected behavior**

The post should be successful and show on the Dev board.

**Screenshots**
![telegram-cloud-photo-size-1-5071121870287383670-y](https://user-images.githubusercontent.com/16282460/235234879-0d94dfc3-87b4-47ca-a47f-f4c4b2e7757a.jpg)

**Desktop (please complete the following information):**
 - OS:  iOS
 - Browser: Brave
 - Version: 1.50.121

**Additional context**

I am submitting from near wallet "efiz.near". This is post the alpha.near.org -> near.org migration. I have successfully posted an idea before. The character length of the description is 5474. I am not replying to a post; there is no parent_id.

**Comment by elliotBraem** [comment] 2023-05-01 19:37
This is a bug on near.org. Works on near.social

**Comment by ori-near** [comment] 2023-05-02 00:32
Hi @elliotBraem – thanks so much for submitting this bug. I saw that you were able to post your message successfully:
https://near.social/#/devgovgigs.near/widget/gigs-board.pages.Post?id=511

So just to clarify for repro step #1: When you went to https://near.org/devgovgigs.near/widget/gigs-board.pages.Feed, the rest of the repro steps above didn't work. But when you went to https://near.social/#/mob.near/widget/MyPage?accountId=devgovgigs.near, the same repro steps worked?

**Comment by frol** [comment] 2023-05-02 15:53
@elliotBraem I have just tried to reproduce the issue, and was able to successfully post [my response](https://near.org/devgovgigs.near/widget/gigs-board.pages.Post?id=511&transactionHashes=xPLrkzrmmk46VoeikusRQ6DptDDLQJgei8dLvmHY1bv#/devgovgigs.near/widget/gigs-board.pages.Post?id=512). I wonder if it was already fixed by the near.org gateway. It does not sound like DevHub issue to me given that it worked just fine on another gateway. Let us know if you keep observing this issue, provide more details about your browser and OS.

**Comment by ori-near** [comment] 2023-05-02 19:50
Closing this ticket since we're unable to reproduce the issue. But please feel free to provide more details if you experience this issue again.

**Closed by ori-near** 2023-05-02 19:50 UTC
Labels: bug
