### ISSUE TITLE
Unable to Create Solution Post

### ISSUE THREAD

**Issue by jtsmedley** [near/neardevhub-widgets#560] opened 2023-12-12 15:59 UTC
**Describe the bug**
When attempting to post a solution or idea to the devhub portal I get the below error.

**To Reproduce**
1. Go to 'https://near.social/devhub.near/widget/app?page=create'
2. Click on 'Submit'
3. Approve the Transaction

**Expected behavior**
Solution posted to site successfully

**Screenshots**
![image](https://github.com/near/neardevhub-widgets/assets/38006759/2b004f11-81be-46ba-b3d2-d35d5a660d6a)

**Desktop:**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome and Brave
 - Version [e.g. 22] 1.61.101 Chromium 1200.6099.71

**Additional context**
Tried with multiple different wallet providers.  Not sure what is unique about my account that is causing the issue.

**Comment by Megha-Dev-19** [comment] 2023-12-12 19:18
hey @jtsmedley, I just tried it and was able to create one (just fyi, we don't display `devhub-test` label posts on UI)
https://nearblocks.io/txns/4NsGxQyvFCgurUUZNj3TmeyECsFegLBsoaPQ74VrTE59#execution
can you please share your txn.?

**Comment by Deepcryptodive** [comment] 2023-12-13 14:08
I am having the exact same issue. I am trying to create a post in DevHub to claim the ETHLisbon hackathon bounty. 

Here is a step-by-step description of what I did:

1) Go to https://near.social/devhub.near/widget/app?page=feed . 
I am logged in there with the Near Wallet on deepcryptodive.near
2) Click Post —> Select 'Solution' and fill in the following information
![image_2023-12-11_17-48-29](https://github.com/near/neardevhub-widgets/assets/61325205/b647710e-b1fb-4d76-adf4-50817eb07ad5)

3) I click 'Submit'
4)  I click Confirm, and then Approve
5) I get this error
![Screenshot from 2023-12-11 16-45-14](https://github.com/near/neardevhub-widgets/assets/61325205/6b4dc433-db7b-4f9f-9ad8-11ddf56aaffe)


The past few days I was messaging with a Near representative regarding the bounty claim, but unfortunately, we couldn't resolve the issue. I also tried seeking assistance in the main Near Telegram channel but haven't found a solution there. I'm really looking forward to resolving this, especially since the hackathon concluded over a month ago. Any support in this matter would be greatly appreciated. If there are technical challenges with the current process, I'll gladly explore alternative methods to claim the bounty.

@Megha-Dev-19 you can see a series of failed transactions here: https://nearblocks.io/address/deepcryptodive.near 

**Desktop:**
OS: Linux Mint (Ubuntu)
Browser: Brave 
Version: [Version 1.60.125 Chromium: 119.0.6045.199 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by Megha-Dev-19** [comment] 2023-12-13 14:19
hey @Deepcryptodive, thanks for providing detailed explanation, will get back to you with the fix asap.

**Closed** 2023-12-13 16:03 UTC
Labels: bug

**Comment by Megha-Dev-19** [comment] 2023-12-13 16:12
hey @jtsmedley @Deepcryptodive please retry, the issue is resolved.

**Comment by jtsmedley** [comment] 2023-12-13 16:16
@Megha-Dev-19 Issue is confirmed fixed.  Thank you for your prompt attention!
