### ISSUE TITLE
Unable to create a DevHub post with Fast Auth wallet.

### ISSUE THREAD

**Issue by Akshay115** [near/neardevhub-widgets#282] opened 2023-09-28 15:38 UTC
Unable to create a DevHub post with Fast Auth wallet.

**Error**
It doesn't display an error. It's just that when I click on '+POST', it doesn't react at all. It doesn't present an option to create a post.

**Expected behaviour**
It should present an option to add posts.

 - Device: Realme 9i .
 - OS: Android 13 .
 - Browser: Brave browser.
 - Version: Brave 1.57.62, Chromium 116.0.5845.180 .

**Comment by ailisp** [comment] 2023-11-24 03:39
The issue is now fixed on Fast Auth side and we can create post with a fast auth account on near.org gateway. But there is another issue with near.org that it interacts with DevHub contract is not reliable and can silently fail or silently succeed, which we're addressing now and will annouce when this support is perfect

**Closed by ailisp** 2023-11-24 03:39 UTC
Labels: bug
