### ISSUE TITLE
Posts missing from the feed

### ISSUE THREAD

**Issue by elliotBraem** [near/neardevhub-widgets#348] opened 2023-10-25 17:26 UTC
**Describe the bug**

I am unable to find a [fellowship proposal](https://near.social/#/devgovgigs.near/widget/gigs-board.pages.Post?id=1469) that had been posted. 

**To Reproduce**
1. Go to DevHub main activity feed.
2. Searched by tag "fellowship-proposal" and by author "james.near"
3. The fellowship proposal does not come up, although it matches either criteria

**Expected behavior**

I should be able to search all posts on DevHub

**Comment by ailisp** [comment] 2023-10-26 09:16
About 1% of posts are not indexed in the database and reported is one of them. Let's name them "problematic posts". I debug run the blocks that contain add/edit problematic posts, but they produce correct dump and post data to insert to database, indicate there is no logic error in the code and failure can be network execution or database connection. Then, there is no failing log about problematic posts or blocks containing problematic posts. I have a proper logging mechanism even when it fails, so the only explanation is that indexer silently fails on these 1% cases without recording anything, include logging, to the database. 

I'm creating a minimum reproduce indexer to confirm the problem and report to indexer team. The best way to fix it maybe is to help query api team fix on their side and rerun the indexer. If that isn't fast enough, I'll also look for quicker workarounds.

**Comment by ailisp** [comment] 2023-10-30 01:40
Reported to Query API team and under investigating: https://github.com/near/queryapi/issues/336

**Comment by ailisp** [comment] 2023-11-09 10:48
The root cause is the contract filter (blocks per contract dump to s3 service) and is just fixed by Query API team. I have deployed a new indexer that have all posts id since ~60:

 https://near.org/dataplatform.near/widget/QueryApi.App?selectedIndexerPath=bo.near/devhub_v27&view=editor-window

For post id < 60 is probably creating post in a different way and it's not seen from indexer logs.

**Comment by ailisp** [comment] 2023-11-10 04:57
The post id < 60 are missing because they use add_idea, add_sponsorship, add_comment, etc. methods and we are only handling add_post. Will see if I can indexed those ones as well

**Comment by jaswinder6991** [comment] 2023-11-10 14:09
Can we close this post or @ailisp @elliotBraem do we want to work on the first 60 post ids to be indexed and then do it?

**Comment by ailisp** [comment] 2023-11-13 08:18
@jaswinder6991 first 60 posts are more challenge than expected to fix, they were created by an older version of contract with add_comment, add_idea, add_solution, etc. methods instead of the single add_post, and then stored in different collections other than the posts vector in contract. And indexer have to handle all these cases. Given recent posts are more important to have than oldest 60 posts, l pull up a fix here: https://github.com/near/neardevhub-widgets/pull/460

will continue working on a good fix for first 60 posts.

**Comment by ailisp** [comment] 2023-11-16 02:32
Now this issue is fixed. All posts are indexed and can be found in feed/search via: #483 #460. Majority work is done in https://github.com/ailisp/devhub-queryapi, we have a tracking issue #480 to migrate it to devhub

**Closed by ailisp** 2023-11-16 02:32 UTC
Labels: bug
